openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Recipe Manager API'
  description: ''
tags:
  - name: 'recipe'
    description: 'Operations on recipes'
  - name: 'book'
    description: 'Operations on books'
  - name: 'tag'
    description: 'Operations on tags'
paths:
  '/user/login':
    $ref: './user.yaml#/~1user~1login'
  '/users':
    $ref: './user.yaml#/~1users'
  '/user':
    $ref: './user.yaml#/~1user'
  '/user/{user_id}':
    $ref: './user.yaml#/~1user~1{user_id}'

  '/recipes':
    $ref: './recipe.yaml#/~1recipes'
  '/recipe':
    $ref: './recipe.yaml#/~1recipe'
  '/recipe/{recipe_id}':
    $ref: './recipe.yaml#/~1recipe~1{recipe_id}'

  '/books':
    $ref: './book.yaml#/~1books'
  '/book':
    $ref: './book.yaml#/~1book'
  '/book/{book_id}':
    $ref: './book.yaml#/~1book~1{book_id}' 
  '/book/{book_id}/recipes':
    $ref: './book.yaml#/~1book~1{book_id}~1recipes'

  '/tags':
    $ref: './tag.yaml#/~1tags' 
  '/tag':
    $ref: './tag.yaml#/~1tag' 
  '/tag/{tag_id}':
    $ref: './tag.yaml#/~1tag~1{tag_id}'