DROP DATABASE IF EXISTS RecipeManager;
CREATE DATABASE RecipeManager;
USE RecipeManager;

CREATE TABLE Users(
  UserID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(40) NOT NULL,
  PasswordHash VARCHAR(64) NOT NULL,
  Role VARCHAR(40) NOT NULL,
  
  PRIMARY KEY (UserID),
  UNIQUE (Name)
);

CREATE TABLE Sessions(
  SessionID VARCHAR(32) NOT NULL,
  CreatedDT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LastAccessedDT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ExpirationDT DATETIME,
  ExpirationMinutes INT DEFAULT 10,
  UserID INT NOT NULL,
  PRIMARY KEY (SessionID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TRIGGER DeleteEx

CREATE TABLE Recipes(
  RecipeID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(40) NOT NULL,
  ActiveTimeMinutes INT,
  TotalTimeMinutes INT,
  Description VARCHAR(300),
  Servings INT,
  UserID INT NOT NULL,
  
  PRIMARY KEY (RecipeID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID)
	ON DELETE CASCADE
);

CREATE TABLE Steps(
  RecipeID INT NOT NULL,
  Ordinal INT NOT NULL,
  Instructions VARCHAR(200) NOT NULL,
  
  PRIMARY KEY (Ordinal, RecipeID),
  FOREIGN KEY (RecipeID) REFERENCES Recipes(RecipeID)
	ON DELETE CASCADE
);

CREATE TABLE Books(
  BookID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(40) NOT NULL,
  
  PRIMARY KEY (BookID)
);

CREATE TABLE Ingredients(
  IngredientID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(40) NOT NULL,
  
  PRIMARY KEY (IngredientID)
);

CREATE TABLE Tags(
  Name VARCHAR(40) NOT NULL,
  
  PRIMARY KEY (Name)
);

CREATE TABLE RecipeIngredients(
  RecipeID INT NOT NULL,
  IngredientID INT NOT NULL,
  Amount FLOAT,
  Unit VARCHAR(10),
  
  PRIMARY KEY (RecipeID, IngredientID),
  FOREIGN KEY (RecipeID) REFERENCES Recipes(RecipeID)
	ON DELETE CASCADE,
  FOREIGN KEY (IngredientID) REFERENCES Ingredients(IngredientID)
	ON DELETE CASCADE
);

CREATE TABLE RecipeTags(
  RecipeID INT NOT NULL,
  TagName INT NOT NULL,
  
  PRIMARY KEY (RecipeID, TagName),
  FOREIGN KEY (RecipeID) REFERENCES Recipes(RecipeID)
	ON DELETE CASCADE,
  FOREIGN KEY (TagName) REFERENCES Tags(Name)
	ON DELETE CASCADE
);

CREATE TABLE BookRecipes(
  BookID INT NOT NULL,
  RecipeID INT NOT NULL,
  
  PRIMARY KEY (RecipeID, BookID),
  FOREIGN KEY (RecipeID) REFERENCES Recipes(RecipeID)
	ON DELETE CASCADE,
  FOREIGN KEY (BookID) REFERENCES Books(BookID)	
	ON DELETE CASCADE
);

CREATE TABLE BookTags(
  BookID INT NOT NULL,
  TagName INT NOT NULL,
  
  PRIMARY KEY (TagName, BookID),
  FOREIGN KEY (TagName) REFERENCES Tags(Name)
	ON DELETE CASCADE,
  FOREIGN KEY (BookID) REFERENCES Books(BookID)
	ON DELETE CASCADE
);